# Generated by Django 6.0 on 2026-02-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_instructorprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorprofile',
            name='photo',
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
