# Generated by Django 6.0 on 2026-02-24 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_completedcontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
    ]
